-- AlterTable
ALTER TABLE  calls ADD COLUMN IF NOT EXISTS connectedAt TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS usedRelay BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS connectionTimeMs INTEGER,
ADD COLUMN IF NOT EXISTS durationMs INTEGER;
